const { Command } = require('@oclif/command');
const createClient = require('../client');
const { load: loadConfig } = require('../core/config');
const cli = require('cli-ux').default;

class JoinCommand extends Command {
  async run() {
    const config = loadConfig();
    const client = await createClient(config);
    const token = await cli.prompt('Please introduce the invitation token you have received');
    await client.joinHub({ username: config.username, token });
    client.disconnect();
  }
}

JoinCommand.description = `Sets up harprocrates
...
This command allows you to join the harpocrates hub for the first time as a non authenticated member.
In order to join a hub you need an invitation token.
Invitation tokens can be generated by users that are already on a hub by using the command: harpocrates invite
`;

JoinCommand.flags = {
};

module.exports = JoinCommand;
